// <auto-generated />
namespace PetLab.DAL.Context
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class root : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(root));
        
        string IMigrationMetadata.Id
        {
            get { return "201509120652043_root"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
