// <auto-generated />
namespace PetLab.DAL.Context
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class last_box : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(last_box));
        
        string IMigrationMetadata.Id
        {
            get { return "201510040718088_last_box"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
